name: 'iotbot sync'

on:
  schedule:
    - cron: '0 */1 * * *'
  watch:
      types: started

jobs:
  iotbot-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 'Install dependencies'
        run: python -m pip install --upgrade pip
      - name: 'Install requirements'
        run: pip install requests
      - name: 'download'
        timeout-minutes: 400
        run: python will_not_cover.py
      - name: 'Commit'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "sync"
      - name: 'Push'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
